# Generated by Django 3.1.2 on 2020-10-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PF_Value_Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('date_ending', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sell')], max_length=1)),
                ('transaction_value', models.FloatField(default=0.0)),
                ('stock_sold', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=1000.0)),
                ('pf_value', models.ManyToManyField(blank=True, to='trading.PF_Value_Daily')),
                ('stocks', models.ManyToManyField(blank=True, to='trading.Stock')),
                ('transactions', models.ManyToManyField(blank=True, to='trading.Transaction')),
            ],
        ),
    ]
