# Generated by Django 3.1.2 on 2020-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
