# Generated by Django 3.1.2 on 2020-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
